controllers/api/users.js
public/mods/directives/user/script.js
public/mods/directives/user/templates/user-picker.html

Pending areas
- Hide & display text box dynamically

User picker directive working

---

controllers/api/clients.js
models/client.js
public/mods/app.js
public/mods/clients/clientsControllerMain.js
public/mods/clients/clientsModule.js
public/mods/clients/clientsRouter.js
public/mods/clients/clientsViewMain.html
routes/apiRoutes.js
routes/pageRoutes.js
services/clients.js
views/misc/clients.ejs
views/partials/include-app.ejs
views/partials/menuSecure.ejs

- with model, services, routes, api endpoints

client template created

---

models/user.js
public/mods/directives/user/script.js
public/mods/directives/user/templates/user-picker.html
public/mods/keynotes/keynotesControllerMain.js
public/mods/keynotes/keynotesViewAdd.html
services/keynotes.js

- User picker integrated
- User model enhanced

Keynotes improved

---

models/feebackDef.js
models/lov.js
models/visit.js
models/visitSchedule.js

- lov, visit, visitSchedule, feedbackDef

data models included

---

data/samples/Json's/client.json
data/samples/Json's/user.json
data/samples/Json's/visit.json
data/samples/Json's/visitSchedule.json
data/samples/PopulateDB.bat

Created each json file for collections(user, client, visit, visitSchedule) & a batch file (PopulateDB.bat)  
for importing the data from the json files & populating the DB at a time.
Steps:
1. Run the batch file(PopulateDB.bat) in data/samples folder under root folder of the application.
2. You'll see the messages on the console while populating the DB.
3. Close the console & check the DB with name "cViz-Test"

Populating DB

---

config/development.json
config/production.json
package.json
routes/main.js
services/users.js

Issue with user add & edit resolved

---

models/client.js
public/mods/clients/clientsControllerMain.js
public/mods/clients/clientsRouter.js
public/mods/clients/clientsViewAdd.html
public/mods/clients/clientsViewMain.html
public/mods/clients/clientsViewShow.html
public/mods/clients/partials/clientsGrid.html
services/clients.js
services/users.js

#issue 63 Client Account Management added multi-populate model,in view pages Add,Edit,Update,Delete functionalities with styles included.

Account mangement 

---

bower.json
views/partials/menuSecure.ejs

- profile path was not working
- bower.json corrupted in kranthis commit

day commit issues resolved

---

html/schedule/schedule.css
html/schedule/schedule.html
views/layouts/schedule.ejs

resolved conflict from routes/mobileRoutes.js
also added schedule timeline changes in cviz/html dir.

resolved conflict from routes/mobileRoutes.js

---

bower.json
models/keynote.js
public/assets/styles/custom-main.css
public/assets/styles/formstyles.css
public/mods/keynotes/keynotesControllerMain.js
public/mods/keynotes/keynotesViewAdd.html
public/mods/keynotes/partials/keynotesGrid.html
views/layouts/main.ejs
views/partials/include-std.ejs

notification styles and keynotes modifications  added

Styles andkeynotes

---

controllers/api/clients.js
models/visit.js
public/mods/clients/clientsViewAdd.html
public/mods/visits/partials/visitsGrid.html
public/mods/visits/partials/visitsViewPanels.html
public/mods/visits/scheduleViewAdd.html
public/mods/visits/visitorsViewAdd.html
public/mods/visits/visitsControllerMain.js
public/mods/visits/visitsModule.js
public/mods/visits/visitsRouter.js
public/mods/visits/visitsViewAdd.html
public/mods/visits/visitsViewMain.html
public/mods/visits/visitsViewShow.html
routes/apiRoutes.js
services/clients.js

Visit planner issue #81 pipeline-2 changes done in Grid, Add page, and Added panel.

---

controllers/api/cityFacts.js
controllers/api/factSheets.js
controllers/api/teasers.js
data/master/PopulateDB.bat
data/master/jsonFiles/group.json
data/master/jsonFiles/lov.json
data/master/jsonFiles/user.json
data/samples/PopulateDB.sh
data/samples/jsonFiles/factSheet.json
data/samples/jsonFiles/teaser.json
data/samples/jsonFiles/user.json
routes/apiRoutes.js
services/cityFacts.js
services/factSheets.js
services/teasers.js

created json files for user, lov & group schemas
run the populateDB.bat file under "data\master\"
user will be created with the credentials :
email: admin@csc.com
password: admin
added comments for the files changed in previous commit

Created Json files for populating master data

---

controllers/api/groups.js
models/group.js
models/user.js
public/mods/admin/users/groupsViewMain.html
public/mods/admin/users/userDialog.html
public/mods/admin/users/usersControllerMain.js
public/mods/admin/users/usersRouter.js
public/mods/admin/users/usersViewMain.html
routes/apiRoutes.js
services/groups.js
views/partials/menuSecure.ejs

Sub Issue Fixed 1,2,3,4,5
1.Created Group Model with fields name,description and user which is reference to user field.
2.Created Restful service for groups.
3.Changes done in user model,adding group as an array to group collections.
4.Adding Group icon in user management page and when clicking on group icon it should show popup with all the group available.
5.Admin can select the group and add the user to particular group which user have access.

Issue No #106 User management Submodule Group

---

public/mods/admin/users/usersControllerMain.js
public/mods/app.js
public/mods/directives/userdisplay/script.js
public/mods/directives/userdisplay/templates/bulletMediumOnlyPanel.html
public/mods/directives/userdisplay/templates/bulletSmallOnlyPanel.html
public/mods/directives/userdisplay/templates/emailOnlyPanel.html
public/mods/directives/userdisplay/templates/largepanel.html
public/mods/directives/userdisplay/templates/mediumpanel.html
public/mods/directives/userdisplay/templates/nameOnlyPanel.html
public/mods/directives/userdisplay/templates/smallpanel.html
public/mods/directives/userdisplay/templates/summaryOnlyPanel.html
public/mods/directives/userdisplay/templates/userdisplay.html
public/mods/profile/profileControllerMain.js
public/mods/profile/profileRouter.js
public/mods/profile/profileViewEdit.html
public/mods/profile/profiledialog.html
views/partials/include-app.ejs

-Added nameOnlyPanel with link to profile edit page for particular user.
-Added emailOnlyPanel,SummaryOnlyPanel,Large Panel,Medium Panel,Small Panel
-Add profile page routes for showing user by id.
-Added profilebyIdControllerMain and profileViewEdit page.

User Display Directive Sub Modules:

---

data/samples/PopulateDB.bat
data/samples/jsonFiles/client.json
data/samples/jsonFiles/group.json
data/samples/jsonFiles/user.json
data/samples/jsonFiles/visit.json
data/samples/jsonFiles/visit_schedule.json
views/home.ejs

added lov.json & group.json in sample data
removed google calendar from dashboard side bar
added 3 users in user.json file

Modified Json Files according to latest data

---

bower.json
public/mods/app.js
public/mods/directives/fileupload/script.js
public/mods/directives/fileupload/templates/fileDialog.html
public/mods/directives/fileupload/templates/fileEntityUpload.html
public/mods/directives/fileupload/templates/fileLocationUpload.html
public/mods/directives/fileupload/templates/fileProfileUpload.html
public/mods/directives/fileupload/templates/fileUpload.html
public/mods/directives/userprofile/script.js
public/mods/profile/profileControllerMain.js
routes/apiRoutes.js
server.js
views/partials/include-app.ejs
views/partials/include-std.ejs

- Validation of file size is done at the time of image is selecting.File size
should be less than the file size specified.
- Rectangular crop area support functionality added
- After cropping of image validation is done based on file size.If cropped image
is too small it wont allow to upload it,
else if cropped image is greater than
the image specified it wont allow.
- ngImgCrop dependencies changed to ngImgCropFullExtended
- created dynamic routes for file upload

Module FileUpload directive with cropping image.

---

public/assets/g/css/confirmDialog.css
public/d/confirmDialog/script.js
public/mods/admin/users/usersViewMain.html
public/mods/app.js
public/mods/clients/partials/clientsGrid.html
public/mods/facts/partials/factsGrid.html
public/mods/feedback/partials/feedbackGrid.html
public/mods/keynotes/partials/keynotesGrid.html
public/mods/visits/partials/visitsGrid.html
views/assets/appAssets.js
views/assets/stdAssetMap.js
views/assets/stdAssets.js

-Confirm Dialog box implemented on user module,fact module,feedback module,
keynote module,visit module whenever clicking on delete ,lock ,unlock button
in those modules.
-Dropzone dependecies included
-Stdassets and appassets modified to include confirmdialog dependencies.

Module Confirm Dialog Directive:

---

public/assets/w/styles/dashboard.css
routes/authRoutes.js
tests/console/menu.js
views/assets/appAssetMap.js
views/assets/appAssets.js
views/home.ejs
views/login.ejs
views/partials/menuSecure.ejs
views/signup.ejs

--> Added standard & app assests in "authRoutes.js" for sign up module
--> Added bottom bar for dashboard page
--> Modified dashboard.css file for right-sidebar & bottom bar
--> Modified menusecure.ejs for profile-menu callout
--> Modifed home.ejs

Fixed Footer issue on sign-up page

---

public/d/clientDisplay/script.js
public/d/clientDisplay/templates/clientLargePanel.html
public/d/clientDisplay/templates/clientMediumPanel.html
public/d/clientDisplay/templates/clientNameOnlyPanel.html
public/d/clientDisplay/templates/clientSmallPanel.html
public/d/clientDisplay/templates/clientdisplay.html
public/mods/app.js
public/mods/visits/partials/visitsGrid.html
public/mods/visits/visitsControllerMain.js
views/assets/appAssets.js

-client display directive with name only and link to client show page.
-done modification in appAssets,appAssetsMap
-added directive clientdisplay directive in app.js cviz-manage module.

Module Client Display Directive:

---

public/d/richText/script.js
public/mods/app.js
views/assets/appAssets.js

-added script.js in directive for changing HTML text to formatted text.
-changes in app.js and appAssets.js to include rich text directive.

Module Rich Text Directive:

---

public/d/clientDisplay/script.js
public/mods/visits/sessions/sessionAddDialog0.html
public/mods/visits/sessions/sessionsControllerMain.js
public/mods/visits/sessions/sessionsList.html
views/assets/stdAssets.js

-fixed auto refresh functionality in sessiongrid  after adding schedule.
-fixed the issue of showing all the session while clicking on all schedule link.
-Removed scrolling from the dialog box,and fixed dialog styles for timeline.

Schedule Enhancement in Schedule Page:

---

public/assets/w/styles/userpicker.css
public/d/userView/script.js
public/d/userView/templates/bulletSmall.html
public/d/userView/templates/userView.html
public/m/app.js
public/m/sessions/sessions.html
views/assets/appAssets.js

-added bulletSmall html page in userView Directive.
-integrated userView directive in sessions.html page

Module userView directive for Mobile

---

data/samples/PopulateDB.bat
data/samples/jsonFiles/feedbackDef.json
data/samples/jsonFiles/visit.json
data/samples/jsonFiles/visit_schedule.json
public/m/sessions/sessions.html
public/m/sessions/sessionsCtrl.js

Added feedbackDef.json for populating feedback templates.
Modified  .bat file according to json
Modified  sessions.html  &  sessionsCtrl.js for showing sessions feedback.

Added Feedback-defs json

---

public/d/user/script.js
public/d/user/templates/largepanel.html
public/d/user/templates/mediumpanel.html
public/d/userDisplay/templates/largepanel.html
public/d/userDisplay/templates/mediumpanel.html
public/mods/clients/clientsViewAdd.html
public/mods/keynotes/keynotesControllerMain.js
public/mods/keynotes/keynotesViewAdd.html
public/mods/visits/sessions/sessionAddDialog0.html
public/mods/visits/sessions/sessionsList.html
public/mods/visits/visitsViewAdd.html
routes/apiRoutes.js

-user picker issue resolved in clients,keynotes,sessions,visits (add,edit page).
-changed the icon to img-circle for user,userDisplay directive for
consistent look and feel.

User Picker Issue Resolved:

---

public/assets/g/css/toaster.css
public/assets/g/js/toaster.js
public/d/feedbackDirective/script.js
public/d/feedbackDirective/templates/feedbackPage.html
views/assets/appAssets.js
views/assets/stdAssetMap.js

-After feedback submission thankyou note is shown in the form of toast
for 3-5 seconds.

Thank you Note after feedback submission..

---

models/visit.js
public/mods/visits/partials/sortSearch.html
public/mods/visits/partials/visitsGrid.html
public/mods/visits/scheduleViewAdd.html
public/mods/visits/visitsControllerMain.js
public/mods/visits/visitsViewAdd.html
services/visits.js

**Visit list :** 
Added date filter
**Visit add :**
1. Added feedback panel, 
2.session panel at finalizer tab.
3.meeting place added at agenda schedule table.

visit planner: issues#18,19,82 in excel sheet.

---

public/d/user/script.js
public/mods/clients/clientsViewAdd.html
public/mods/contactList/contactListViewMain.html
public/mods/keynotes/keynotesViewAdd.html
public/mods/visits/inviteesAdd.html
public/mods/visits/sessions/sessionAddDialog0.html
public/mods/visits/visitsViewAdd.html

-created one more attribute field userType which different CSC/
Non CSC Employees.
-able to show user is Edit Mode and can validate whether CSC/Non
CSC employee also.
-changes done in ClientAdd,KeynoteAdd,VisitAdd,InviteesAdd,SessionAdd,
ContactListAdd HTML Pages.

Issue No 7,74,75 User Picker Issues

---

data/master/jsonFiles/user.json
data/samples/jsonFiles/factSheet.json
data/samples/jsonFiles/teaser.json
data/samples/jsonFiles/user.json
models/user.js
public/m/home/welcome.html

Modified user.json & user.js in models
Modified welcome.html for video playblack
Modified teaser, factsheet json files

Issue No.96

---

public/mods/admin/users/partials/sortSearch.html
public/mods/admin/users/usersRouter.js
public/mods/admin/users/usersViewMain.html
public/mods/admin/users/usersViewPanels.html
public/mods/clients/clientsRouter.js
public/mods/clients/clientsViewPanels.html
public/mods/clients/partials/clientsGrid.html
public/mods/clients/partials/sortSearch.html
public/mods/contactList/contactListRouter.js
public/mods/contactList/contactListViewMain.html
public/mods/contactList/contactListViewPanels.html
public/mods/contactList/partials/sortSearch.html
public/mods/facts/factsRouter.js
public/mods/facts/factsViewPanels.html
public/mods/facts/partials/factsGrid.html
public/mods/facts/partials/sortSearch.html
public/mods/feedback/feedbackRouter.js
public/mods/feedback/feedbackViewPanels.html
public/mods/feedback/partials/feedbackGrid.html
public/mods/feedback/partials/sortSearch.html
public/mods/keynotes/keynotesViewPanels.html
public/mods/keynotes/partials/keynotesGrid.html
public/mods/keynotes/partials/sortSearch.html
public/mods/visits/partials/visitsGrid.html

Across all UI pages added Detail/panel view functionality

CVM - IssueList#1

---

public/mods/visits/partials/visitsGrid.html

cvmissuelist#1 - typo mistake

---

models/visitSchedule.js
public/mods/visits/profilePictureDialog.html
public/mods/visits/sessions/sessionAddDialog0.html
public/mods/visits/sessions/sessionsControllerMain.js
public/mods/visits/sessions/sessionsList.html
public/mods/visits/visitorsViewAdd.html
public/mods/visits/visitsControllerMain.js

-In Add Visit-> Add Visitor added attribute for comparing csc/non csc
employees.
-Added Dropdowns for start time ,end time in Visit Schedule
dialog.Validating Start Time and end time in Visit Schedule Dialog.
- Getting Prepopulated Location and Feedback Template in Visit
Schedule from Visit Data.Able to change default location and
feedback template.
- Creted blank template for non exisiting user in add visitor
tab.

Issue No 16,76,83,99:

---

public/d/userProfile/templates/user-profile.html
public/mods/profile/profileViewEdit.html

cvm issue 35 label changes

---

public/mods/admin/users/groupsViewMain.html
public/mods/admin/users/usersControllerMain.js

cvm issue 91- Add/edit group functionality implemented

cvm issue 91- Add/edit group functionality implemented

---

public/assets/m/css/sessions.css
public/m/sessions/sessions.html
views/layouts/mmain-mobile.ejs

Added horizontal scrolling functionality of schedule days

Scrollable Day Div

---

public/mods/admin/users/usersViewMain.html
public/mods/admin/users/usersViewPanels.html
public/mods/clients/clientsViewPanels.html
public/mods/clients/partials/clientsGrid.html
public/mods/contactList/contactListViewPanels.html
public/mods/facts/factsViewPanels.html
public/mods/facts/partials/factsGrid.html
public/mods/feedback/feedbackViewPanels.html
public/mods/keynotes/keynotesViewPanels.html
public/mods/keynotes/partials/keynotesGrid.html

cvm issue 1- 
1) removed adv. search button from panel view and 
2) fixed alignment issues

cvm issue 1- removed adv. search button from panel view and fixed alignment issues

---

public/d/invitees/script.js
public/mods/clients/clientsViewAdd.html
public/mods/facts/factsViewAdd.html
public/mods/feedback/feedbackViewAdd.html
public/mods/keynotes/keynotesViewAdd.html
public/mods/visits/sessions/sessionAddDialog0.html
public/mods/visits/sessions/sessionsControllerMain.js
public/mods/visits/sessions/sessionsList.html
public/mods/visits/visitsViewAdd.html

-added invitee directive in visit schedule.
-added confirm dialog directive for cancel button in
all the add forms.

Issue no 51,76-Confirm Dialog Directive and Invite Directive Addition

---

public/d/userProfile/templates/user-profile.html
public/mods/feedback/itemViewDialog.html
public/mods/visits/sessions/sessionAddDialog0.html
public/mods/visits/visitorsViewAdd.html

- added form validation in feedback page,keynotes,schedule..
- fixed the styles in feedback templates.
- added contact no field in user profile directive.

Issue no 42,46,47,49:

---

public/mods/clients/clientsViewAdd.html
public/mods/facts/factsViewAdd.html
public/mods/feedback/feedbackViewAdd.html
public/mods/keynotes/keynotesViewAdd.html
public/mods/visits/visitsViewAdd.html

- fixed issue of the header,subheader info in all the add new forms ,
edit existing forms.

Issue no 90,91,109 for showing proper header info in ADD,EDIT Mode

---

public/mods/visits/sessions/sessionAddDialog0.html

cvm issue 2 and style changes for submit and cancel button

cvm issue 2 and style changes

---

public/assets/w/styles/dialogButton.css
public/mods/admin/users/userDialog.html
views/assets/appAssets.js

Style changes for Add user and cancel button

cvm issue #8 - add User to Group button style

---

public/mods/keynotes/partials/keynotesGrid.html

Removed tfooter from Manage-> Keynotes grid

cvm issue 110

---

models/group.js
public/assets/w/styles/dataview-table.css
public/assets/w/styles/dialogButton.css
public/mods/admin/users/groupsViewMain.html
public/mods/admin/users/userDialog.html
public/mods/admin/users/usersControllerMain.js

cvm issue#111
1) Advanced Search button functionality not working - FIXED
2) Implement Delete group functionality - DONE
3) increase text box width - DONE
4) Add group form validation - DONE
5) add user to group dialog box style changes - DONE

cvm issue#111

---

data/samples/jsonFiles/user.json
services/visits.js

Modified User emails
Modified visit.js in services

Modified user Json

---

models/feedbacks.js
public/d/feedbackDirective/script.js
public/d/feedbackDirective/templates/feedbackPage.html
public/m/sessions/sessions.html
public/m/sessions/sessionsCtrl.js

- Integrated session wise feedback based on session feedback template
- added session id field in model for feedbacks.

Session wise feedback:

---

data/samples/jsonFiles/feedbackDef.json
data/samples/jsonFiles/visit_schedule.json
models/client.js
models/factSheets.js
models/group.js
models/user.js
models/visitSchedule.js

Resolved issue while adding client
modified jsn files
modified models & removed required = true where it is not necessary

Resolved issues while adding client

---

controllers/api/cityFacts.js
models/factSheets.js
public/m/city/city.html
public/m/city/cityCtrl.js
public/m/city/main.html
public/m/facts/facts.js
public/m/facts/factsCtrl.js
routes/apiRoutes.js
services/cityFacts.js
views/assets/appAssets.js

- added city facts module in mobile side.
- modified api routes,controllers,services in cityFacts
to get city Facts data by name.

City Facts added for Mobile Side

---

public/m/facts/facts.js
public/m/facts/factsCtrl.js
public/m/facts/main.html
public/m/facts/segments/certs.html
public/m/facts/segments/indiaLocs.html
public/m/facts/segments/qFacts.html

- Added Dropdown with select option to choose segments wise
facts.
- Added page routes for segments in factsCtrl.js

Segment Wise Facts Page Added

---

scripts/secure.js
tests/console/menu.js
tests/console/secure.js
views/assets/menuDef.js

secure.getGroups and secure.isInAnyGroup fixed
side menu and user role issues fixed

secure module fixed

---

models/feedbackDef.js
public/mods/feedback/feedbackViewAdd.html
public/mods/visits/sessions/sessionAddDialog0.html
public/mods/visits/sessions/sessionsControllerMain.js
public/mods/visits/sessions/sessionsList.html
public/mods/visits/visitsControllerMain.js

- Schedule Date Format Modified while adding schedule in visit
- In Schedule Page for (All hyperlink) hiding the Add New Schedule button
- Heading for Session Type

Schedule Date Format Modified while adding schedule

---

data/samples/jsonFiles/client.json
data/samples/jsonFiles/feedbackDef.json
data/samples/jsonFiles/visit.json

Minor changes in json data

---

public/mods/visits/visitsControllerMain.js

- added orgRef field while adding visitors.
- allowing only visitors to be added in add visitor tab who are of type Client in agenda page.

Visitor Issues fixed

---

data/samples/jsonFiles/user.json
data/samples/jsonFiles/visit.json
data/samples/jsonFiles/visit_schedule.json
models/client.js

minor changes in visit & visit_schedule.json files

minor changes in visit & visit_schedule.json files

---

data/samples/jsonFiles/visit.json
data/samples/jsonFiles/visit_schedule.json

new schedule added for testing

new schedule added

---

data/master/PopulateDB.bat
data/master/PopulateDB.sh
data/master/jsonFiles/cityFacts.json
data/samples/PopulateDB.bat
data/samples/PopulateDB.sh

City facts added for remaining 4 cities..
City facts removed from samples & replaced in master DB

City facts added

---

data/samples/jsonFiles/visit.json
data/samples/jsonFiles/visit_schedule.json
public/mods/visits/sessions/sessionAddDialog0.html
public/mods/visits/sessions/sessionsControllerMain.js
services/visits.js

Modified zone in sessions
Modified visit.js service to sort the sessions according to start time.

Modified Zone in sessions, Sessions order

---

data/master/jsonFiles/user.json
data/samples/jsonFiles/user.json

Designation Modified for Visit Managers & admin

Designation Modified

---

data/samples/jsonFiles/user.json
public/d/feedbackDirective/script.js
public/d/userDisplay/templates/designation.html
public/mods/visits/sessions/sessionsControllerMain.js
public/mods/visits/sessionwiseFeedback.html
public/mods/visits/visitsControllerMain.js
public/mods/visits/visitsFeedbackMode.html
public/mods/visits/visitwiseFeedback.html

-Fixed feedback saving issue when tea,lunch,dinner..

-Visit Wise,Session Wise Feedback mode added in admin side..

---

public/d/clientDisplay/templates/clientNameOnlyPanel.html
public/mods/visits/sessions/sessionAddDialog0.html
public/mods/visits/sessions/sessionsControllerMain.js
public/mods/visits/sessions/sessionsList.html
public/mods/visits/sessionwiseFeedback.html
public/mods/visits/visitsControllerMain.js

-View Feedback Issues Fixed for Owner and Supporter.
-Added Validation in Schedule Dialog for speaker and supporter.
-Added Validation in Schedule Dialog for start time,end time,session type and
meeting rooms.

Feeback issues and session validation added..

---

controllers/api/meetingPlaces.js
models/meetingPlaces.js
public/mods/app.js
public/mods/keynotes/keynotesModule.js
public/mods/meetingPlaces/meetingPlacesControllerMain.js
public/mods/meetingPlaces/meetingPlacesModule.js
public/mods/meetingPlaces/meetingPlacesRouter.js
public/mods/meetingPlaces/meetingPlacesViewMain.html
public/mods/meetingPlaces/partials/meetingPlacesViewPanels.html
public/mods/meetingPlaces/partials/sortSearch.html
public/mods/visits/sessions/sessionAddDialog0.html
public/mods/visits/sessions/sessionsControllerMain.js
routes/apiRoutes.js
services/meetingPlaces.js
views/assets/appAssets.js
views/partials/menuSecure.ejs

-added meetingPlaces routes,api,services
-added menu for meeting places in customize tab.
-validation added in edit schedule dialog.
-able to retreive meetingPlaces in schedule dialog based on location
added in meetingPlaces HTML Page..

meetingPlaces added,schedule Dialog Edit Validation Issue Fixed:

---

public/assets/w/styles/tooltip.css
public/d/tooltipDirective/script.js
public/mods/admin/users/groupsViewMain.html
public/mods/admin/users/partials/usersViewPanels.html
public/mods/admin/users/usersViewMain.html
public/mods/app.js
public/mods/clients/partials/clientsGrid.html
public/mods/clients/partials/clientsViewPanels.html
public/mods/contactList/contactListViewMain.html
public/mods/facts/partials/factsGrid.html
public/mods/facts/partials/factsViewPanels.html
public/mods/feedback/partials/feedbackGrid.html
public/mods/feedback/partials/feedbackViewPanels.html
public/mods/keynotes/partials/keynotesGrid.html
public/mods/keynotes/partials/keynotesViewPanels.html
public/mods/meetingPlaces/meetingPlacesViewMain.html
public/mods/teasers/partials/teasersGrid.html
public/mods/teasers/partials/teasersPanel.html
public/mods/visits/partials/visitsGrid.html
public/mods/visits/partials/visitsViewPanels.html
public/mods/visits/sessions/sessionsList.html
views/assets/appAssets.js

-Tooltip directive added for all the links(glyphicons) to show custom message about functionality.

Tooltip Directive Added

---

public/mods/app.js
public/mods/lovs/lovsControllerMain.js
public/mods/lovs/lovsModule.js
public/mods/lovs/lovsRouter.js
public/mods/lovs/lovsViewAdd.html
views/assets/appAssets.js
views/partials/menuSecure.ejs

Added lovs module
Modified menusecure.js, app.js, appAssests.js

Added List of Values page

---

public/mods/lovs/lovsControllerMain.js

Added Growl messages & validations while adding & deleting lovs

Modified lovsControllerMain.js

---

models/keynote.js
public/d/user/script.js
public/d/user/templates/largepanel.html
public/d/user/templates/mediumpanel.html
public/d/user/templates/smallpanel.html
public/d/user/templates/user-picker.html
public/m/home/homeCtrl.js
public/m/home/welcome.html
public/mods/keynotes/keynotesControllerMain.js
public/mods/keynotes/keynotesViewAdd.html
public/mods/visits/sessions/sessionAddDialog0.html
public/mods/visits/sessions/sessionsControllerMain.js
routes/apiRoutes.js
services/keynotes.js
services/visits.js

-User Picker Issue Fixed.
-Multiple Signatory Added in keynotes mobile side and web side.

Keynotes Signatory added and user picker issue fixed.

---

public/mods/visits/sessions/sessionAddDialog0.html
public/mods/visits/sessions/sessionsList.html

Modified sessionAddDialog0.html
Modified sessionList.html

Applied media quires for session dialog

---

controllers/api/users.js
public/assets/w/styles/angucomplete.css
public/d/autoComplete/angucomplete.js
public/d/autoComplete/script.js
public/d/autoComplete/templates/largepanel.html
public/d/autoComplete/templates/mediumpanel.html
public/d/autoComplete/templates/smallpanel.html
public/d/autoComplete/templates/user-picker.html
public/mods/app.js
public/mods/keynotes/keynotesViewAdd.html
public/mods/visits/sessions/sessionAddDialog0.html
routes/apiRoutes.js
services/users.js
views/assets/appAssets.js

- Added service for seraching by first name,last name,email.
- Added new autocomplete directive.

AutoComplete User directive added for keynotes and sessions.

---

data/master/jsonFiles/lov.json
public/mods/lovs/lovsControllerMain.js
public/mods/lovs/lovsViewAdd.html
public/mods/visits/sessions/sessionAddDialog0.html
public/mods/visits/sessions/sessionsControllerMain.js
public/mods/visits/visitsControllerMain.js
views/login.ejs

Added sessiontype in LOVs
removed horizontal line in login page

Added Session types in LOVs

---

data/samples/jsonFiles/visit_schedule.json
public/mods/visits/agendaTab.html
public/mods/visits/sessions/sessionsControllerMain.js
public/mods/visits/sessions/sessionsList.html
public/mods/visits/visitsControllerMain.js

Added speaker column in session grid
Modified dropdown values for business-type existing
Modified error messages

Resolved issues - 5,8,11

---

public/d/autoComplete/templates/largepanel.html
public/d/autoComplete/templates/mediumpanel.html
public/d/autoComplete/templates/smallpanel.html
public/mods/keynotes/keynotesControllerMain.js
public/mods/keynotes/keynotesViewAdd.html
public/mods/meetingPlaces/meetingPlacesControllerMain.js
public/mods/meetingPlaces/meetingPlacesViewMain.html
public/mods/visits/visitorsTab.html

- keynote validation added for same signatory added.
- designation autocomplete field changed.
- MeetingPlace dropdown Added

Keynote val

---

models/visit.js
public/mods/clients/clientInclude.html
public/mods/clients/clientsControllerMain.js
public/mods/visits/agendaTab.html
public/mods/visits/partials/visitsGrid.html
public/mods/visits/visitorsTab.html
public/mods/visits/visitsControllerMain.js
public/mods/visits/visitsViewAdd.html

save draft,new client notitifation,createdBy should not change, sponcer deleted.

---

public/assets/w/styles/angucomplete-alt.css
public/d/autoComplete/angucomplete-alter1.js
public/d/userDisplay/script.js
public/d/userDisplay/templates/association.html
public/m/home/homeCtrl.js
public/m/home/welcome.html
public/mods/app.js
public/mods/visits/agendaTab.html
public/mods/visits/visitorsTab.html
public/mods/visits/visitsControllerMain.js
views/assets/appAssets.js

-differentiation added in visitor table for csc executives and clients.
-client name included in welcome note.

-Autocomplete styling issue fixed

---

public/mods/visits/agendaTab.html
public/mods/visits/visitsControllerMain.js

Visit Page - visitor type issue fixed

Visit Page - visitor type issue fixed

---

bower.json
data/master/jsonFiles/lov.json
data/samples/jsonFiles/client.json
models/visit.js
public/mods/visits/agendaTab.html
public/mods/visits/businessOppDetails.html
public/mods/visits/visitsControllerMain.js
public/mods/visits/visitsModule.js
views/assets/stdAssetMap.js
views/assets/stdAssets.js

Added Business opportunity details & visiting any competitor

Issue 5,8,11

---

controllers/api/clients.js
models/client.js
models/visit.js
public/d/autoComplete/angucomplete-alt.js
public/d/autoComplete/templates/user-picker.html
public/mods/clients/clientInclude.html
public/mods/clients/clientsControllerMain.js
public/mods/visits/agendaTab.html
public/mods/visits/businessOppDetails.html
public/mods/visits/partials/visitsGrid.html
public/mods/visits/scheduleViewAdd.html
public/mods/visits/visitorsTab.html
public/mods/visits/visitsControllerMain.js
public/mods/visits/visitsViewAdd.html
services/clients.js
views/assets/stdAssets.js

Visit planner:
Added SFDCId autocompleate.
issue fixed on Net Promoter Score scroll removed.
Issue fixed draft status (admin/emp).
Added edit for bods at visit planner.
Added readonly for client field when wip.
client module:
Added dropdown for regions,
Issue fixed for client edit.

issue fixed @ visit planner WN22

---

public/mods/feedback/itemViewDialog.html
public/mods/visits/agendaTab.html

net promoter score is validated
Feedback item closing issue fixed

minor issues fixed

---

public/mods/visits/scheduleViewAdd.html
public/mods/visits/visitsControllerMain.js

Issue 52.b - edit start date and end date in visit screen fixed

Issue 52.b - edit start date and end date in visit screen fixed

---

public/mods/visits/agendaTab.html
public/mods/visits/partials/visitsGrid.html
public/mods/visits/uploadFiles.html
public/mods/visits/visitorsTab.html
public/mods/visits/visitsRouter.js
services/clients.js

Visit Initiator cannot be able to edit any details after submit.

issue no.23 fixed

---

public/assets/w/styles/layout.css

growl notifications fixed

---

public/mods/visits/scheduleViewAdd.html
public/mods/visits/visitsControllerMain.js

Commented edit dates

---

models/visitSchedule.js
public/d/invitees/script.js
public/d/invitees/templates/invitee.html
public/mods/visits/sessions/sessionAddDialog0.html
public/mods/visits/sessions/sessionsControllerMain.js

Session feedback - added feedback functionality for session invitees

Issue 34B - Session feedback - added feedback functionality for session invitees

---

public/d/invitees/script.js
public/d/invitees/templates/invitee.html
public/mods/visits/sessions/sessionsControllerMain.js

Edit functionality of invitees feedback fixed.

Edit functionality of invitees feedback fixed.

---

services/visits.js

modified visit stats service

---

public/mods/visits/partials/sortSearch.html
public/mods/visits/visitsControllerMain.js
services/visits.js

Removed unwanted buckets like lastweek, nextweek etc
visits count in all bucket

Modified visit buckets

---

models/visit.js
public/d/ssnFeedbackDir/ssnfeedback.html
public/d/ssnFeedbackDir/ssnfeedback.js
public/m/overallFeedback/overallFeedback.html
public/m/overallFeedback/overallFeedback.js
public/m/sessions/sessions.html
public/m/sessions/sessionsCtrl.js
public/mods/visits/overallFeedbacks.html
public/mods/visits/partials/visitsGrid.html
public/mods/visits/valFinal.html
public/mods/visits/visitsControllerMain.js
public/mods/visits/visitsRouter.js
public/mods/visits/visitsViewAdd.html
public/mods/visits/vmanCheck.html

1.Session level feedback fixed.
2.Overall feedback fixed.
3.vManagers involved visits list ready.

WN24- #issue 34.a, WN25-#issue 52.c fixed from FunctionReviewFeedback excel sheet.

---

data/samples/jsonFiles/lov.json
models/visit.js
public/assets/w/styles/userpicker.css
public/mods/visits/agendaTab.html
public/mods/visits/businessOppDetails.html
public/mods/visits/scheduleViewAdd.html
public/mods/visits/visitorsTab.html

WN-25 #108 - Bucketization of Visit Initiation Screen done.

WN-25 #108 - Bucketization of Visit Initiation Screen done.

---

public/m/overallFeedback/overallFeedback.js
public/mods/visits/partials/sortSearch.html
public/mods/visits/partials/visitsGrid.html
public/mods/visits/visitsControllerMain.js

Visit manager able ot see all the visits irrespective of the visits assigned to him..

Issue no. 14.b

---

data/master/jsonFiles/lov.json

WN- 25 - added lov.json values

WN- 25 - added lov.json values

---

public/mods/visits/visitorsTab.html
public/mods/visits/visitsControllerMain.js

WN-25 Issue#108- Bucketization for visit initiat screen
Password need to be visible only to Admin/ VM is fixed.

WN-25 Issue#108- Bucketization for visit initiat screen

---

public/mods/clients/clientInclude.html
public/mods/clients/partials/clientsGrid.html
public/mods/feedback/partials/feedbackGrid.html
public/mods/keynotes/partials/keynotesGrid.html
public/mods/visits/sessions/sessionAddDialog0.html
services/visits.js

modified view icon for all the items in manage tab
fixed drop down issue in session add dialog

Resolved Minor issues regarding wn24

---

models/visit.js
public/d/ssnFeedbackDir/ssnfeedback.js
public/mods/visits/agendaTab.html

fixed net promoter score

---

public/d/userDisplay/templates/nameWithoutHref.html
public/mods/visits/partials/visitsGrid.html
public/mods/visits/sessions/printAgenda.html

changed overallfeedback icon in visit grid

changed overallfeedback icon in visit grid

---

public/mods/visits/vmanCheck.html
services/visits.js

visits stats will show both primary & secondary visit managers if assigned for a visit

Added secondary Visit manager in visit stats

---

bower.json
public/assets/w/styles/print.css
public/assets/w/styles/printCustom.css
public/mods/visits/sessions/printAgenda.html
public/mods/visits/sessions/sessionsControllerMain.js
public/mods/visits/sessions/sessionsList.html
public/mods/visits/visitsModule.js
views/assets/stdAssetMap.js
views/assets/stdAssets.js

WN-25 Issue#181 - Option to fire a print the agenda etc. from the backend
Added print button to print agenda page

WN-25 Issue#181 - Option to fire a print the agenda etc. from the backend

---

views/partials/menuSecure.ejs

WN-26 Issue #137 - Add Visit button on the top (blue band) is removed.

WN-26 Issue #137 - Add Visit button on the top (blue band) is removed.

---

public/assets/w/styles/userpicker.css
public/mods/visits/agendaTab.html
public/mods/visits/finalizeTab.html
public/mods/visits/visitorsTab.html

WN-26 Issue#111 - All the mandatory fields to be marked with a red *

WN-26 Issue#111 - All the mandatory fields to be marked with a red *

---

public/mods/visits/agendaTab.html

WN-26 issue#111 All the mandatory fields to be marked with a red *

WN-26 issue#111 All the mandatory fields to be marked with a red *

---

public/assets/w/styles/userpicker.css
public/mods/visits/agendaTab.html

WN-24 - Issue 108- bucketization
Changed in labels, alignment and UI issues

WN-24 - Issue 108- bucketization

---

models/client.js

WN-26 Issue 204 - Parent and child account name to remain the way initiator submit it.

WN-26 Issue 204 - Parent and child account name to remain the way initiator submit it.

---

public/assets/m/css/welcome.css
public/d/userProfile/templates/user-profile.html
public/m/home/home.html
public/m/home/homeCtrl.js
public/m/home/welcome.html
public/m/overallFeedback/thankyou.html
public/m/sessions/session.html
public/m/sessions/sessionsCtrl.js
public/mods/visits/sessions/sessionAddDialog0.html
public/mods/visits/sessions/sessionsControllerMain.js
public/mods/visits/visitorsTab.html
public/mods/visits/visitsControllerMain.js

userList issue rectified for new added customer in add user tab
feedback button style improved in home page
welcome message improved in welcome screen
session notes styles improved in session page
speaker field made mandatory in session page of website
thankyou page style improved and page modified

Issue No 62,201,216,227

---

public/assets/w/styles/userpicker.css
public/d/userProfile/templates/user-profile.html
public/mods/visits/agendaTab.html
public/mods/visits/visitorsTab.html

1) UI alignment issues
2) added * mark for visitor profile

WN 24- Issue 108 - Bucketization changes includes

---

controllers/api/visits.js
public/m/home/home.html
public/m/home/homeCtrl.js
public/m/overallFeedback/overallFeedback.html
services/visits.js

feedback button hiding/unhiding based on last day last session time added in home page - issue no 238
feedback error message removed from overallfeedback - issue no 249
service added to get last day last session time in visit service.

issue no 238,249

---

public/mods/visits/empagenda.html

label changes and UI issuee

---

models/visit.js
public/mods/visits/agendaTab.html
public/mods/visits/cancelVisit.html
public/mods/visits/empagenda.html
public/mods/visits/partials/visitsGrid.html
public/mods/visits/visitorsTab.html
public/mods/visits/visitsControllerMain.js
public/mods/visits/vmanEdt.html

1. reject visit fixed.
2. #issue 203 save as draft fixed.
3. fixed styles in cancel visit.

 #issue 203 save as draft fixed

---

public/m/sessions/sessionsCtrl.js
public/m/visits/myVisits.html

When a session is dropped, it should update the time of following sessions also.
solved the date and the box (with Past, Future and Today) overlapping by the top bar.

solved issue no. #246,254

---

public/mods/visits/agendaTab.html
public/mods/visits/visitsControllerMain.js

1. issue #118 logo for vmanager is fixed.
2. overall feed back for clients feedback comes- fixed

Logo for vmanager, overall feedback

---

public/m/contacts/contacts.html
public/m/contacts/contactsCtrl.js

Added Filter functionality on Contact page

Added Filter functionality on Contact page

---

public/mods/visits/agendaTab.html
public/mods/visits/empagenda.html
public/mods/visits/overallFeedbacks.html
public/mods/visits/partials/visitsGrid.html
public/mods/visits/sessions/visitPanel.html
public/mods/visits/uploadFiles.html
public/mods/visits/visitsControllerMain.js
public/mods/visits/visitsViewAdd.html

WN-26 Issue 110 - Title form visit screen to be removed

WN-26 Issue 110 - Title form visit screen to be removed

---

data/master/PopulateDB.bat
data/master/PopulateDB.sh
data/master/jsonFiles/cityFacts.json
public/m/city/city.html

Added city Facts for new locations
Modified dropdown for scrolling locations

Added city Facts for new locations

---

public/assets/w/styles/printCustom.css
public/assets/w/styles/userpicker.css
public/mods/visits/sessions/printAgenda.html
public/mods/visits/sessions/sessionsList.html

Alignment changes fixed
CSC and Client Image changes fixed.

issue 181 - Print for "All" and "Date" wise agenda fixed.

---

public/m/sessions/sessions.html
public/m/sessions/sessionsCtrl.js

Added validation for push session
push button is enabled only if the mins <, > 0

Added validation for push session

---

public/assets/w/styles/userpicker.css
public/mods/clients/clientsControllerMain.js
public/mods/visits/agendaTab.html
public/mods/visits/businessOppDetails.html
public/mods/visits/empagenda.html
public/mods/visits/finalizeTab.html
public/mods/visits/partials/visitsGrid.html
public/mods/visits/scheduleViewAdd.html
public/mods/visits/visitAdd.html
public/mods/visits/visitorsTab.html
public/mods/visits/visitsControllerMain.js
public/mods/visits/visitsViewAdd.html
public/mods/visits/visitsViewMain.html
public/mods/visits/vmanEdt.html
views/partials/menuSecure.ejs

Issue 179 - message, alignment in overall frame

Issue 179 - message, alignment in overall frame

---

public/assets/w/styles/printCustom.css
public/mods/visits/sessions/printAgenda.html

Issue - 181 - print UI and functionality changes

Issue - 181 - print UI and functionality changes

---

public/mods/visits/agendaTab.html
public/mods/visits/empagenda.html
public/mods/visits/visitAdd.html
public/mods/visits/visitorsTab.html
public/mods/visits/visitsControllerMain.js
public/mods/visits/vmanEdt.html

Issue 179 - Changes in Messages.

Issue 179 - Changes in Messages.

---

public/assets/w/styles/print.css
public/assets/w/styles/printCustom.css

print preview changes

---

public/m/visitsAdd/add.js
public/m/visitsAdd/agendaTab.html
public/m/visitsAdd/scheduleVisit.html
services/visits.js

resvolved client duplication while creating a visit
resolved visit initiation in mobile

resolved visit initiation in mobile

---

GruntFile.js

removed case sensitive for .png file extensions

grunt file modified

---

public/mods/admin/users/usersControllerMain.js
public/mods/admin/users/usersViewMain.html

Group Field Removed for customer

Customer Association Issue Fixed

---

services/visits.js

1. mobile side executive bios.
2. overall feedback eligibility at portal side.

Duplicate employees fixed at

---

public/mods/clients/clientsControllerMain.js

solved client name selection from drop down
previoulsy when parent name & child name r selected from dropdown after saving the parent name & child name both used to be the same
files changed : public/mods/clients/clientControllerMain.js

resolved client name selection issue

---

public/mods/clients/clientsControllerMain.js
public/mods/visits/visitsControllerMain.js

Fixed "You said the information was" status.

---

public/assets/m/css/welcome.css
public/d/userView/templates/detailView.html
public/m/home/welcome.html
public/m/visits/myVisits.html

modified view for today's date in my visits page
modified client logo in welcome note

Modified todays date view & bios div

---

public/m/visitsAdd/add.js
public/m/visitsAdd/visitInformation.html

2. visit init mobile- client fields without clicking dropdowns issue fixed.

1. Client objective field replaced with CSC objective field

---

public/m/app.js
public/m/home/home.html

CSC personnels should navigate to active visit form my visits page
resvolved Contacts path from homepage
files touched: 
public/m/app.js
public/m/home/home.html

removed active visit for CSC personnels (5 users in visit initiation)

---

public/d/invitees/script.js
public/d/invitees/templates/invitee.html
public/d/userDisplay/script.js
services/visits.js

2.Remove all visitors from a visit, application is crashing because of exception in getParticipantById
3.In session edit, remove an invitee at top; it removes at bottom

Tracker issues 1,2,3 fixed

---

public/mods/clients/clientInclude.html
public/mods/clients/clientsControllerMain.js
public/mods/visits/closeSummary.html
public/mods/visits/overallFeedbacks.html
public/mods/visits/partials/visitsGrid.html
public/mods/visits/visitsControllerMain.js
public/mods/visits/visitsRouter.js

1.issue # 51- overall feedback list of users is displayed on refresh of browser for newly added users. fixed
2.issue # 52- client edit/add only by admin. but could be done by clicking client directive fixed.
3.visit close summary page ready.

Fixed issues-51,52 form tracker excel, added client close summary page.

---

public/m/home/homeCtrl.js

resvolved issue When there are 2 welcome notes for a visit

Welcome Note issue fixed

---

public/d/invitees/script.js
public/mods/visits/partials/visitsGrid.html
public/mods/visits/visitsControllerMain.js

1. All vist details not visible after visit close.
2. Comma separated emails for invitees added.

Fixed 96,97 issues in spreedsheet tracker

---

controllers/api/visits.js
services/visits.js

Fetching offering heads & regions heads for the selected offerings & regions in a visit.
files touched: services/visit.js
controllers/visit.js

fetching offering & regions heads

---

controllers/api/visits.js
public/mods/visits/sessionwiseFeedback.html
public/mods/visits/visitsControllerMain.js
services/visits.js

removed VM's,session speaker & owner from exec. bios
removed code fragments in session descrption in view feedbacks

removed VM's,session speaker & owner from exec. bios

---

scripts/email.js

issue#63 - Agenda PDF changes

---

templates/email/welcomeClient/html.swig
templates/email/welcomeClient/text.swig

Modified Client auto login URL in mail

Added Client auto login URL in mail

---

public/d/invitees/script.js
public/d/invitees/templates/invitee.html
public/m/sessions/sessions.html
public/m/sessions/sessionsCtrl.js
services/visits.js

1.Invitees checkbox session elg feedback fixed.
2.Thankyou keynote made mandetory  at plannig stage at visit planner web portal.

Invitees session feedback fixed, made Thankyou  note mandetory at visit planner.

---

controllers/api/visitSessionTemplates.js
models/visitSessionTemplates.js
public/mods/visits/sessions/sessionAddDialog0.html
public/mods/visits/sessions/sessionsControllerMain.js
routes/apiRoutes.js
services/visitSessionTemplates.js

- Session Search Template Added,Save as New Template and Update Template feature implemented in add schedule for visit

issue no 10 fixed

---

public/d/userView/templates/nameWithoutHref.html
public/m/sessions/session.html

Issue #96 - displaying first name last name and date changes in session notes

Issue #96 - displaying first name last name and date changes in session notes

---

public/assets/m/css/sessions.css
public/assets/w/styles/print.css
public/assets/w/styles/printCustom.css
public/m/sessions/sessionNotes.html
public/mods/visits/sessions/printAgenda.html

Print and session notes alignment changes

Print and session notes alignment changes

---

scripts/email.js
services/visits.js
tests/console/email.js

Visit invitees wont be the part of exec. bios section from now..

Removed visit invitees form exec. bios section

---

public/d/header/title.html

#issue 8 Modified

---

public/assets/m/css/header.css
public/d/header/title.html

scrollable Header subtitle
fixed issue in firefox

Issue #8 Resolved

---

public/mods/feedback/feedbackControllerMain.js
scripts/email.js
services/visits.js
tests/console/email.js

Modified getOfferingHeads & getRegionsHeads services
Removed rootscope service from feedback controller
Modified email.js

Removed rootscope service from feedback controller

---

public/d/ssnFeedbackDir/ssnfeedback.html
public/m/sessions/session.html
public/m/sessions/sessionsCtrl.js
public/m/visits/myVisits.html
views/login.ejs

client cannot see session notes
removed feedback eligibility by default for customer

Issue #91,#14 fixed

---

public/m/sessions/sessions.html

Hiding move session link for cancelled/dropped session

Session push/pull & cancel scenerio

---

config/development.json
controllers/api/emails.js
public/mods/admin/users/userDialog.html
public/mods/admin/users/usersControllerMain.js
routes/validateRequest.js
scripts/email.js
services/visits.js

- User Add to group checkbox issue solved and req.url issue solved for vmanager,exec,user 403 Forbidden error.
-email notification for push session

Cviz security issue

---

public/mods/clients/clientInclude.html
public/mods/visits/notificationsTab.html

added styl;e for client logo & removed second Notification button in notification tab

added styl;e for client logo & removed second Notification button

---

public/m/sessions/sessionNotes.html
public/mods/facts/factsControllerMain.js

session notes user directive issue resolved.
Signed-off-by: Kranthi <krekam@csc.com>

session notes user directive issue resolved.

---

public/m/home/homeCtrl.js

resolved logout, factsheets, & feedback icos loading issues for client
Signed-off-by: Kranthi <krekam@csc.com>

resolved logout, factsheets, & feedback icos loading issues for client

---

bower.json
config/app.js
controllers/api/users.js
controllers/api/visits.js
public/assets/w/styles/paginationStyles.css
public/mods/admin/users/usersControllerMain.js
public/mods/admin/users/usersViewMain.html
public/mods/app.js
public/mods/visits/partials/visitsGrid.html
public/mods/visits/sessions/sessionsControllerMain.js
public/mods/visits/visitsControllerMain.js
routes/apiRoutes.js
services/appService.js
services/users.js
services/visits.js
views/assets/appAssets.js
views/assets/stdAssets.js

Added pagination in visit & user module
Modified required files & added pagination styles, app.js
Signed-off-by: Vinod Chilukuru <vchilukuru@asiapac.globalcsc.net>

Added pagination in visit & user module
